### ISSUE TITLE
config.h

### ISSUE THREAD

**Issue by proshagger** [mtwb47/dwmricer#6]
I wanted to tweak some of the keybinds so i want to know where is config.h located and the dwm.
ty :)

**Comment by mtwb47** [comment]
Once you've run the script, you can go to $HOME/.config/suckless/dwm and you'll find it there. Remember to edit the config.def.h file. Delete config.h and then edit the .def.h file so that when you make && sudo make install, the new bindings will be transferred over to the new config.h file that will be built. 

Let me know if you need more help.

Matt

**Comment by proshagger** [comment]
problem is that i cant find any files in there.

[EDIT] and modkey and enter dosent open the terminal (alacritty)

**Comment by mtwb47** [comment]
So you downloaded the script. Ran it, right? Were you able to actually go into dwm? (like log out of whatever WM or DE you were using and then change into dwm)?

If so, the files have to be there. If not, then the script didn't run properly.

If you can't actually get into dwm, clone this repo here https://github.com/mtwb47/suckless  in your config file. 

cd .config 
git clone https://github.com/mtwb47/suckless
cd suckless/dwm
make
sudo make install
(Do the same thing for dmenu and st)
Move the .dwm folder from the suckless folder into your $HOME directory.

Then see if you can get into dwm. You should then also be able to remove config.h and edit config.def.h then make && sudo make install again.

**Comment by proshagger** [comment]
i just ran the scrip once more it was a problem on my part i had some stuff turned off now it works perfectly and all the files are here tyvm for the awesome script you made keep up the good work :).

**Comment by mtwb47** [comment]
Glad you got it to work!
